SET(CMAKE_C_COMPILER   clang)
SET(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/wasi-sdk-20.0/share/wasi-sysroot/)
SET(CMAKE_SYSROOT ${CMAKE_CURRENT_LIST_DIR}/wasi-sdk-20.0/share/wasi-sysroot/)
set(CMAKE_C_FLAGS "--target=wasm32-wasi -I${CMAKE_CURRENT_LIST_DIR}/wasi_mocks -D_WASI_EMULATED_MMAN ${CMAKE_C_FLAGS}")

set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${CMAKE_SYSROOT}/include")

set(CMAKE_C_FLAGS_DEBUG "")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_AR "llvm-ar" CACHE FILEPATH "llvm-ar")
set(CMAKE_RANLIB "llvm-ranlib" CACHE FILEPATH "llvm-ranlib")

set(CMAKE_EXE_LINKER_FLAGS "-lwasi-emulated-mman ${CMAKE_CURRENT_LIST_DIR}/wasi_mocks/pwd.o ${CMAKE_CURRENT_LIST_DIR}/wasi_mocks/posix_mocks.o ${CMAKE_EXE_LINKER_FLAGS}")