name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  detectonly:
    name: Detect use of .only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Detect use of .only
        run: |
          grep -rq --include '*.spec.js' \.only\( . && echo 'You have .only() in your tests!' && exit 1
          exit 0
  default:
    name: "Default"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Default
        run: |
          npm install
          sh setup.sh
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          source ./emsdk/emsdk_env.sh
          cd emscriptenbuild
          ./build.sh Release
          cd ..
          set -e
          npm run test
          npm run test-browser
  asyncify:
    name: Asyncify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Default
        run: |
          npm install
          sh setup.sh
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          source ./emsdk/emsdk_env.sh
          cd emscriptenbuild
          ./build.sh Release-async
          cd ..
          set -e
          npm run test-browser-async
