name: Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  default:
    name: "Default"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Default
        run: |
          npm install
          sh setup.sh
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          source ./emsdk/emsdk_env.sh
          cd emscriptenbuild
          ./build.sh Release
          cd ..
          set -e
          npm run test
          npm run test-browser
          export VERSION=`npm view wasm-git dist-tags.latest`
          export NEWVERSION=`node -p "require('./package.json').version"`
          echo $VERSION $NEWVERSION
          ./preparepublishnpm.sh  
          PACKAGEFILE=`npm pack | tail -n 1`
          tar -xvzf $PACKAGEFILE
          rm test-browser/lg2.*
          echo "run browser tests with npm package"
          cp package/lg2.* test-browser/
          npm run test-browser
          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$VERSION" = "$NEWVERSION" || "$BRANCH" != "master" ]]; then
            echo "version change is $VERSION->$NEWVERSION, branch is $BRANCH, not publishing, only dry-run"
            npm publish --dry-run
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
